flowercollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('main_app.urls')),
    path('accounts/', include ('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('flowers/', views.FlowerList.as_view(), name='flower_list'),
    path('flowers/<int:pk>/', views.FlowerDetail.as_view(), name='flower_detail'),
    path('flowers/create/', views.FlowerCreate.as_view(), name='flower_create'),
    path('flowers/<int:pk>/update/', views.FlowerUpdate.as_view(), name='flower_update'),
    path('flowers/<int:pk>/delete/', views.FlowerDelete.as_view(), name='flower_delete'),
    path('flowers/<int:flower_id>/add_watering', views.add_watering, name='add_watering'),
    path('flowers/<int:flower_id>/add_photo', views.add_photo, name='add_photo'),

    path('accounts/signup/', views.signup, name='signup'),

    path('pollinators/', views.PollinatorList.as_view(), name='pollinator_list'),
    path('pollinators/<int:pollinator_id>/', views.pollinator_detail, name='pollinator_detail'),
    path('pollinators/create/', views.PollinatorCreate.as_view(), name='pollinator_create'),
    path('pollinators/<int:pk>/update/', views.PollinatorUpdate.as_view(), name='pollinator_update'),
    path('pollinators/<int:pk>/delete/', views.PollinatorDelete.as_view(), name='pollinator_delete'),
    path('pollinators/<int:pollinator_id>/assoc_flower/<int:flower_id>/', views.assoc_flower, name='assoc_flower'),
    path('pollinators/<int:pollinator_id>/unassoc_flower/<int:flower_id>/', views.unassoc_flower, name='unassoc_flower'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Flower (models.Model) :

    STAGES = (
        ('S', 'Seed'),
        ('G', 'Germination'),
        ('F', 'Flowering'),
        ('P', 'Pollination'),
    )

    name = models.CharField(max_length=100)
    color = models.CharField(max_length=50)
    description = models.TextField(max_length=200)
    stage = models.CharField(max_length=1, choices=STAGES, default=STAGES[0][0])

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__ (self) :
        return self.name
    
    def get_absolute_url (self) :
        return reverse('flower_detail', kwargs = {'pk': self.id})
    

class Pollinator (models.Model) :

    TYPES = (
        ('Be', 'Bumblebee'),
        ('Wa', 'Wasp'),
        ('Bu', 'Butterfly'),
        ('Mo', 'Moth'),
        ('Fl', 'Fly'),
        ('Bi', 'Bird')
    )

    name = models.CharField(max_length=50)
    description = models.TextField(max_length=100)
    type = models.CharField(max_length=2, choices=TYPES, default=TYPES[0][0])

    flowers = models.ManyToManyField(Flower)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__ (self) :
        return self.name
    
    def get_absolute_url (self) :
        return reverse('pollinator_detail', kwargs = {'pollinator_id': self.id})
    

class Watering (models.Model) :
    date = models.DateField()
    inches = models.IntegerField(default=1)

    flower = models.ForeignKey(Flower, on_delete=models.CASCADE)

    def __str__ (self) :
        return f'{self.date}: {self.inches} of water'
    
    class Meta :
        ordering = '-date',


class Photo (models.Model) :
    url = models.CharField(max_length=250)
    flower = models.ForeignKey(Flower, on_delete=models.CASCADE)

    def __str__ (self) :
        return f'Photo for flower_id: {self.flower_id} @{self.url}'

main_app/forms.py
from django.forms import ModelForm
from .models import Watering

class WateringForm (ModelForm) :
    class Meta :
        model = Watering
        fields = ('date', 'inches')

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, ModelFormMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .models import Flower, Pollinator, Photo
from .forms import WateringForm


import os
import uuid
import boto3


# Create your views here.

# view functions
def home (request) :
    return render(request, 'home.html')

def signup (request) :
    # handling POST request
    if request.method == 'POST' :
        form = UserCreationForm(request.POST)
        if form.is_valid () :
            user = form.save()
            login(request, user)
            return redirect('flower_list')
        
    # handling GET request
    form = UserCreationForm()
    return render(request, 'registration/signup.html', {
        'form': form
    })

def add_watering (request, flower_id) :
    form = WateringForm(request.POST)
    if form.is_valid () :
        new_watering = form.save(commit=False)
        new_watering.flower_id = flower_id
        new_watering.save()
    return redirect('flower_detail', pk=flower_id)

def assoc_flower (request, pollinator_id, flower_id) :
    if Flower.objects.get(id=flower_id).stage == 'P' :
        pollinator = Pollinator.objects.get(id=pollinator_id)
        pollinator.flowers.add(flower_id)
        return redirect('pollinator_detail', pollinator_id=pollinator_id)

def unassoc_flower (request, pollinator_id, flower_id) :
    pollinator = Pollinator.objects.get(id=pollinator_id)
    pollinator.flowers.remove(flower_id)
    return redirect('pollinator_detail', pollinator_id=pollinator_id)

def add_photo (request, flower_id) :
    # collect photo submission from request
    photo_file = request.FILES.get('photo-file', None) # specifies to return None if photo-file is not present
    if photo_file :
        # s3 client object
        s3 = boto3.client('s3')
        # unique name/key for photo file
        key = uuid.uuid4().hex[:10] + photo_file.name[photo_file.name.rfind('.'):]
            # replaces photo file name with hex code, while maintaining .png, .jpeg, etc.
        try :
            # try to upload to aws s3
            s3.upload_fileobj(photo_file, os.environ['BUCKET'], key)
            # generate unique url for image
            url = f'https://{os.environ["BUCKET"]}.s3.amazonaws.com/{key}'
            # save url as new instance of photo model, associate flower
            Photo.objects.create(url=url, flower_id=flower_id)
        except Exception as error :
            print('photo upload failed')
            print(error)
    return redirect('flower_detail', pk=flower_id)

# CBV for Flower
class FlowerList (LoginRequiredMixin, ListView) :
    template_name = 'flowers/flower_list.html'

    def get_queryset (self) :
        return Flower.objects.filter(user=self.request.user)

class FlowerDetail (LoginRequiredMixin, ModelFormMixin, DetailView) :
    template_name = 'flowers/flower_detail.html'
    form_class = WateringForm

    def get_queryset (self) :
        return Flower.objects.filter(user=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super(FlowerDetail, self).get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

class FlowerCreate (LoginRequiredMixin, CreateView) :
    model = Flower
    fields = ('name', 'color', 'description', 'stage')
    template_name = 'flowers/flower_form.html'

    def form_valid (self, form) :
       form.instance.user = self.request.user
       return super().form_valid(form)

class FlowerUpdate (LoginRequiredMixin, UpdateView) :
    fields = ('name', 'color', 'description', 'stage')
    template_name = 'flowers/flower_form.html'

    def get_queryset (self) :
        return Flower.objects.filter(user=self.request.user)

class FlowerDelete (LoginRequiredMixin, DeleteView) :
    success_url = '/flowers/'
    template_name = 'flowers/flower_confirm_delete.html'

    def get_queryset (self) :
        return Flower.objects.filter(user=self.request.user)
    

# CBV for Pollinator
class PollinatorList (LoginRequiredMixin, ListView) :
    template_name = 'pollinators/pollinator_list.html'

    def get_queryset (self) :
        return Pollinator.objects.filter(user=self.request.user)

# class PollinatorDetail (LoginRequiredMixin, DetailView) :
#     template_name = 'pollinators/pollinator_detail.html'

#     def get_queryset (self) :
#         return Pollinator.objects.filter(user=self.request.user)
    
#     def get_context_data(self, **kwargs):
#         context = super(PollinatorDetail, self).get_context_data(**kwargs)
#         context['flowers'] = Flower.objects.all()
#         return context

@login_required
def pollinator_detail (request, pollinator_id) :
    pollinator = Pollinator.objects.get(id=pollinator_id)
    pollinated_flower_ids = pollinator.flowers.all().values_list('id')
    available_flowers = Flower.objects.exclude(id__in=pollinated_flower_ids)

    return render(request, 'pollinators/pollinator_detail.html', {
        'pollinator': pollinator,
        'flowers': available_flowers
    })
    
class PollinatorCreate (LoginRequiredMixin, CreateView) :
    model = Pollinator
    fields = ('name', 'description', 'type')
    template_name = 'pollinators/pollinator_form.html'

    def form_valid (self, form) :
        form.instance.user = self.request.user
        return super().form_valid(form)

class PollinatorUpdate (LoginRequiredMixin, UpdateView) :
    fields = ('name', 'description', 'type')
    template_name = 'pollinators/pollinator_form.html'

    def get_queryset (self) :
        return Pollinator.objects.filter(user=self.request.user)

class PollinatorDelete (LoginRequiredMixin, DeleteView) :
    success_url = '/pollinators/'
    template_name = 'pollinators/pollinator_confirm_delete.html'

    def get_queryset (self) :
        return Pollinator.objects.filter(user=self.request.user)

main_app/templates/flowers/flower_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
<title>Are you sure you want to delete {{ object.name.capitalize }}?</title>
{% endblock %}


{% block content %}
<h1>Are you sure you want to delete {{ object.name.capitalize }}?</h1>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete {{ object.name.capitalize }}" class="button is-danger is-outlined is-rounded">
    <a href="{% url 'flower_detail' object.id %}" class="button is-outlined is-rounded">Cancel</a>
</form>

{% endblock %}

main_app/templates/flowers/flower_detail.html
{% extends 'base.html' %}
{% load bulma_tags %}

{% block content %}

        <div>
            <h2>{{ flower.name.capitalize }}</h2>
            <p>{{ flower.color.capitalize }}</p>
            <p>{{ flower.description }}</p>
            <p>{{ flower.get_stage_display }} stage</p>
            <div>
                <a href="{% url 'flower_update' flower.id %}" class="button is-small is-warning is-light">Update</a>
                <a href="{% url 'flower_delete' flower.id %}" class="button is-small is-danger is-light">Delete</a>
            </div>
        </div>
        <div>
            {% for photo in flower.photo_set.all %}
                <img src="{{ photo.url }}" alt="{{ flower.name }}">
            {% empty %}
                <span>No Photos Uploaded</span>
            {% endfor %}
        </div>
        <form action="{% url 'add_photo' flower.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="photo-file" class="button is-text">
            <input type="submit" value="Upload Photo" class="button is-success is-light">
        </form>

        <br>
        <br>
        <div>
            <h3>Watering Log</h3>
            <form action="{% url 'add_watering' flower.id %}" method="POST"  class="form-small">
                {% csrf_token %}
                <table>
                    {{ form|bulma }}
                </table>
                <input type="submit" value="Water" class="button is-success is-outlined is-rounded">
            </form>
            <table class="table">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Inches of Water</th>
                    </tr>
                </thead>
                <tbody>
                    {% for watering in flower.watering_set.all %}
                        <tr>
                            <td>{{ watering.date }}</td>
                            <td>{{ watering.inches }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


{% endblock %}

main_app/templates/flowers/flower_form.html
{% extends 'base.html' %}
{% load bulma_tags %}

{% block title %}
    {% if object %}
        <title>Update {{ object.name }}</title>
    {% else %}
        <title>Add a Flower</title>
    {% endif %}
{% endblock %}


{% block content %}
    {% if object %}
        <h2>Update {{ object.name }}</h2>
    {% else %}
        <h2>Create a Flower</h2>
    {% endif %}

    <div class="container form-medium">
        <form class="is-horizontal" method="POST">
            {% csrf_token %}
            <table class="mb-4">
                {{ form|bulma }}
            </table>
            <input type="submit" value="Submit" class="button is-success is-outlined is-rounded">
        </form>
    </div>


{% endblock %}

main_app/templates/flowers/flower_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container is-max-desktop">
    {% for flower in object_list %}
    
        <div class="card mb-5 p-0">
            <div class="card-content">
                <a href="{% url 'flower_detail' flower.id %}">
                    <p class="card-header-title p-0">{{ flower.name.capitalize }}</p>
                    <div class="ml-4">
                        <p>{{ flower.color.capitalize }}</p>
                        <p>{{ flower.description.capitalize }}</p>
                        <p>{{ flower.get_stage_display }} stage</p>
                    </div>
                </a>
            </div>
        </div>
    
    {% endfor %}
</div>

{% endblock %}